# Generated by Django 5.0.6 on 2024-06-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='designation_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
