# Generated by Django 5.0.6 on 2024-06-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='updated_by',
        ),
    ]
